name: Playwright Tests
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run Dockerfile with Playwright
        run: docker-compose -f docker-compose.yml up -d
        env:
          CI: 1

      - name: list file in dir 1
        run: |
          sudo ll -la

      - name: Run UI-tests
        run: |
          docker compose -f docker-compose.yml exec pw npm run test || true

      - name: list file in dir 2
        run: |
          sudo ll -la

      - name: Copy history from gh-pages to allure-results before run Allure-generate
        run: |
          sudo rsync -av --delete ./.github/gh-pages/history/ ./allure-results/history

      - name: Generate Allure report to allure-report
        run: docker compose -f docker-compose-pytest.yml exec pw allure generate --clean

      - name: list file in dir 3
        run: |
          sudo ll -la

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
